### PR TITLE
Expect a handler factory, rather than instance.

### PR DESCRIPTION
**Pull request by timuralp**
The users of the ContainerCrawler library may want to perform arbitrary
configuration of the handler instance. As opposed to passing the class,
ContainerCrawler library should expect a factory instance to create
handlers as necessary.

### CODE REVIEW

**Comment by timuralp** [comment]
Note this breaks the current API and downstream clients would need to be updated to work with the new version of the library.

**Comment by timuralp** [comment]
Sure, but we usually tag the release later. I'll follow the same release plan here and bump the version at that time.

**Comment by mdegerne** [comment]
Version is in setup.py which is why I assumed it would be done with the code. Nevertheless, the code change is reasonable.

**Comment by timuralp** [comment]
Merging this change and will tag a new version of ContainerCrawler.

**Pull request merged**
