### PR TITLE
Add prefix argument to list_containers

### PR DESCRIPTION
**Pull request by thiagodasilva**
The `prefix` will be helpful when adding support to crawl sharded containers. For a given container as: `AUTH_acct/container`, the shards will be named `.shards_AUTH_acct/container-<MD5(container)>-<timestamp>-<N>`. the `prefix` parameter is thus used to list only a specific set of shards for that hidden account.

### CODE REVIEW

**Comment by mdegerne** [comment]
It's not obvious to me how the prefix setting helps here. Can you explain?

**Comment by tipabu** [comment]
All shard containers get named similarly. So if you've got `AUTH_acct/containter`, the shards will be named `.shards_AUTH_acct/container-<MD5(container)>-<timestamp>-<N>`, and by listing `.shards_AUTH_acct?prefix=container-` you'll find all the shards (as well as all the shards for `AUTH_acct/container-2` and `AUTH_acct/container-3` 🙁 )

**Comment by thiagodasilva** [comment]
@mdegerne updated the commit message to have it explain why we are adding the `prefix` argument.

**Comment by timuralp** [comment]
Would be great to add a small test that ensures prefix, when set, is plumbed through correctly.

**Pull request merged**
