### PR TITLE
Handle pre-2.18 Swift releases.

### PR DESCRIPTION
**Pull request by timuralp**
2.18 Swift introduced container sharding and the accompanying helper
methods. As the ContainerCrawler can be used with older versions of
Swift, we have to be careful about calling these methods.

Writing a test for this is a little bit difficult, as we need to have
some set of functional tests that we can execute against arbitrary
versions of Swift.

### CODE REVIEW

**Comment by timuralp** [comment]
I can add a test like that, but it's gonna solve only this particular problem. It'd be great to setup some functional tests against various Swift versions longer term.

**Comment by clayg** [comment]
As a matter of process we already run container-crawler tests against old swifts:

**Comment by tipabu** [comment]
LOL! https://github.com/swiftstack/container-crawler/blob/0.1.5/test/unit/test_container_crawler.py#L46

Testing with old swift would be more useful if we didn't mock out quite so much...

**Comment by timuralp** [comment]
I think we need different kind of tests with a NOOP handler and then we can run them against various swifts.

**Pull request merged**
