### PR TITLE
Pass workers when setting up the handler instance.

### PR DESCRIPTION
**Pull request by timuralp**
Container crawler should pass the number of workers when setting up the
handler instance, so that the required resources can be sized correctly
(if applicable).

### CODE REVIEW

**Comment by timuralp** [comment]
I'm actually not sure now if we should change this interface. We have access to the full config in the factory classes. Maybe it would make more sense to fix it there.

**Comment by thiagodasilva** [comment]
@timuralp just took a quick look, I think it would make sense just to make a change to `instance` method in `SyncContainerFactory`, is that what you were thinking?

**Comment by timuralp** [comment]
@thiagodasilva yep -- check out the other related PR.

**Comment by timuralp** [comment]
This is not necessary, as the handlers have access to the full configuration.

**Pull request closed without merging**
